local github = "https://github.com/"

return {
	github .. "nvim-lua/plenary.nvim",
	github .. "nvim-neotest/nvim-nio",
	github .. "ellisonleao/gruvbox.nvim",
	github .. "echasnovski/mini.nvim",
	github .. "folke/flash.nvim",
	github .. "chaoren/vim-wordmotion",
	github .. "neovim/nvim-lspconfig",
	github .. "barreiroleo/ltex_extra.nvim",
	github .. "b0o/schemastore.nvim",
	{ src = github .. "nvim-treesitter/nvim-treesitter", version = "main" },
	github .. "windwp/nvim-ts-autotag",
	github .. "danymat/neogen",
	github .. "mfussenegger/nvim-dap",
	github .. "jbyuki/one-small-step-for-vimkind",
	github .. "rcarriga/nvim-dap-ui",
	github .. "theHamsta/nvim-dap-virtual-text",
	github .. "Civitasv/cmake-tools.nvim",
	github .. "lewis6991/gitsigns.nvim",
	{ src = github .. "NeogitOrg/neogit", version = "master" },
	github .. "sindrets/diffview.nvim",
	github .. "akinsho/git-conflict.nvim",
	github .. "vigemus/iron.nvim",
	github .. "mfussenegger/nvim-lint",
	github .. "stevearc/conform.nvim",
	github .. "linux-cultist/venv-selector.nvim",
	github .. "chrisgrieser/nvim-rulebook",
	github .. "nvim-pack/nvim-spectre",
	github .. "linrongbin16/gitlinker.nvim",
	github .. "lewis6991/async.nvim",
	github .. "ThePrimeagen/refactoring.nvim",
	{ src = github .. "ThePrimeagen/harpoon", version = "harpoon2" },
}
