local create_cmd = vim.api.nvim_create_user_command

create_cmd("BreakpointToggle", function()
  require("dap").toggle_breakpoint()
end, {})
create_cmd("Debug", function()
  require("dap").continue()
end, {})
create_cmd("DapREPL", function()
  require("dap").repl.open()
end, {})

vim.keymap.set("n", "<F5>", function()
  require("dap").continue()
end)
vim.keymap.set("n", "<F10>", function()
  require("dap").step_over()
end)
vim.keymap.set("n", "<F11>", function()
  require("dap").step_into()
end)
vim.keymap.set("n", "<F12>", function()
  require("dap").step_out()
end)
